# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardz', '0002_auto_20191025_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_contact',
            new_name='user',
        ),
    ]
