# Generated by Django 2.2.6 on 2019-10-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardz', '0003_auto_20191025_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
