# Generated by Django 2.2.6 on 2019-10-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ardz', '0004_remove_profile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_cont', models.CharField(max_length=120)),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ardz.Profile')),
                ('commented_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ardz.Projects')),
            ],
        ),
    ]
